In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv(r"YOUR_LOCATION")
dataset

,Id,OptionType,Strike,Spot,TimeToExpiry,RiskfreeRate,MarketFearIndex,BuySellRatio,OptionPrice
0,1,Put,120,148.558157,0.944954,2.720659,71.285594,0.487120,2.877919
1,2,Put,80,118.158570,1.723779,4.873176,64.524904,3.444798,11.626476
2,3,Call,90,108.090156,0.411624,5.082002,76.619034,3.750903,27.088208
3,4,Put,90,111.602240,1.951201,5.923971,95.871987,0.319245,4.629991
4,5,Put,150,56.343242,0.878590,3.307863,46.758397,1.031902,90.974035
...,...,...,...,...,...,...,...,...,...
9995,9996,Put,110,93.604069,1.402202,4.373892,6.579450,0.716937,15.969333
9996,9997,Put,150,128.921187,1.327478,3.671062,14.664286,3.716935,28.652963
9997,9998,Put,130,149.113703,0.364902,3.730788,86.857349,3.110948,11.881759
9998,9999,Call,80,134.230541,1.411376,5.937343,17.958159,0.957441,49.882046
9999,10000,Call,100,72.157920,0.755958,5.550251,14.680883,3.587788,0.891095

In [3]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error as RMSE
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [4]:
x_train = dataset[['OptionType','Strike','Spot','TimeToExpiry','RiskfreeRate','MarketFearIndex','BuySellRatio']]
x_train = x_train.replace('Put',0)
x_train = x_train.replace('Call',1)
x_train

,OptionType,Strike,Spot,TimeToExpiry,RiskfreeRate,MarketFearIndex,BuySellRatio
0,0,120,148.558157,0.944954,2.720659,71.285594,0.487120
1,0,80,118.158570,1.723779,4.873176,64.524904,3.444798
2,1,90,108.090156,0.411624,5.082002,76.619034,3.750903
3,0,90,111.602240,1.951201,5.923971,95.871987,0.319245
4,0,150,56.343242,0.878590,3.307863,46.758397,1.031902
...,...,...,...,...,...,...,...
9995,0,110,93.604069,1.402202,4.373892,6.579450,0.716937
9996,0,150,128.921187,1.327478,3.671062,14.664286,3.716935
9997,0,130,149.113703,0.364902,3.730788,86.857349,3.110948
9998,1,80,134.230541,1.411376,5.937343,17.958159,0.957441
9999,1,100,72.157920,0.755958,5.550251,14.680883,3.587788

In [5]:
y_train = dataset[['OptionPrice']]
y_train

      OptionPrice
0        2.877919
1       11.626476
2       27.088208
3        4.629991
4       90.974035
...           ...
9995    15.969333
9996    28.652963
9997    11.881759
9998    49.882046
9999     0.891095

[10000 rows x 1 columns]

In [ ]:

for i in range(1,15):
    poly = PolynomialFeatures(degree = i)
    x_poly = poly.fit_transform(x_train)
    lin_model = LinearRegression()
    lin_model.fit(x_poly,y_train)
    y_pred = lin_model.predict(x_poly)
    r2 = r2_score(y_train,y_pred)
    mse = RMSE(y_train,y_pred)
    print(f"The r2 score for {i} is {r2}")
    print(f"The MSE for {i} is {mse}")

The r2 score for 1 is 0.037347343463462135
The MSE for 1 is 512.6794092421089
The r2 score for 2 is 0.9859083130305901
The MSE for 2 is 7.504802175162936
The r2 score for 3 is 0.9944175073358235
The MSE for 3 is 2.9730651255516682
The r2 score for 4 is 0.9974993973931409
The MSE for 4 is 1.3317445898360551
The r2 score for 5 is 0.9986662720230564
The MSE for 5 is 0.7103027937088429
The r2 score for 6 is 0.9989883562411839
The MSE for 6 is 0.5387705743204478
The r2 score for 7 is 0.9991045396443233
The MSE for 7 is 0.47689484159295914
The r2 score for 8 is 0.9988407403353867
The MSE for 8 is 0.6173862981383255

In [7]:
from sklearn.linear_model import Ridge
  # Try smaller degrees
poly = PolynomialFeatures(degree=7)
x_poly = poly.fit_transform(x_train)
    
ridge_model = Ridge(alpha=0.1)  # Add regularization
ridge_model.fit(x_poly, y_train)
y_pred = ridge_model.predict(x_poly)
    
r2 = r2_score(y_train, y_pred)
mse = RMSE(y_train, y_pred)
print(f"Degree {7}, RÂ²: {r2}, RMSE: {np.sqrt(mse)}")

Degree 7, RÂ²: 0.9930243663138044, RMSE: 1.9274359892942512

In [8]:
#poly1 = PolynomialFeatures(degree=7)
#x_poly1 = poly.fit_transform(x_train)

lin_model = LinearRegression()
lin_model.fit(x_poly,y_train)
y_pred = lin_model.predict(x_poly)

r2Score = r2_score(y_train,y_pred)
MSE = RMSE(y_train,y_pred)
print(f"Degree {7}, RÂ²: {r2Score}, RMSE: {np.sqrt(MSE)}")

Degree 7, RÂ²: 0.9991045396443233, RMSE: 0.6905757319751101

In [9]:
print(MSE)

0.47689484159295914

In [13]:
poly

PolynomialFeatures(degree=7)

In [18]:
wasd = np.array([[0,110,93.604069,1.402202,4.373892,6.579450,0.716937],[1,60,148.1797401,1.243255425,3.1980597,6.436489684,1.068700429]])
x_wFeatures = poly.fit_transform(wasd)
y_predicted_output = lin_model.predict(x_wFeatures)
y_predicted_output

array([[15.64315692],
       [84.42419828]])

In [21]:
y_train.head(10)

   OptionPrice
0     2.877919
1    11.626476
2    27.088208
3     4.629991
4    90.974035
5    30.600073
6    37.265585
7     6.106726
8    96.095930
9     9.431290

In [22]:
y_pred[:10]

array([[ 2.50568422],
       [11.48237294],
       [25.82161941],
       [ 2.97863759],
       [91.76998268],
       [32.36212689],
       [37.60108186],
       [ 7.13126189],
       [97.45060715],
       [10.95204488]])